# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_title', models.CharField(max_length=500)),
                ('anime_sypnosis', models.CharField(max_length=3000)),
                ('anime_genre', models.CharField(max_length=350)),
                ('anime_logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
